In [30]:
import numpy as np
import pandas as pd

In [31]:
df = pd.read_csv("hepsiemlak.csv")

In [32]:
df['cityDistNeig'] = df['listingCard__media-link href'].apply(lambda x : x.split('/')[3])

In [33]:
df['district'] = df['cityDistNeig'].apply(lambda x:x.split('-')[1])
df['neighborhood'] = df['cityDistNeig'].apply(lambda x:x.split('-')[2:-1])

In [34]:
df['neighborhood'] = df['neighborhood'].apply(lambda x:"_".join(x))

In [ ]:
def dropColumn(df,colName):
    """ 
    sütünları siler

    parameters
    df = data frame 

    colName = column Name sütun adı
    """
    try:
        df.drop(colName,axis=1,inplace=True)
    except Exception as e:
        print(e)

In [36]:
dropColumn(df,'listingCard__media-link href')

In [37]:
silinecekler = ['listingCard__photo-index', 'listingCard__date',
       'listingCard__title', 'listingCard__spec-item', 'listingCard__spec-sep 4',
       'listingCard__spec-label 5',
       'listingCard__location', 'wp-btn-label', 'he-lazy-image src',
       'he-lazy-image src 2', 'listingCard__owner-firm', 'cityDistNeig',]

In [38]:
dropColumn(df,silinecekler)

In [39]:
df = df[df['listingCard__spec-item 2']!='Stüdyo']

In [40]:
df['room'] = df['listingCard__spec-item 2'].apply(lambda x:x.split('+')[0])
df['living_room'] = df['listingCard__spec-item 2'].apply(lambda x:x.split('+')[1])

In [41]:
dropColumn(df,'listingCard__spec-item 2')

In [42]:
df['area'] = df['listingCard__spec-item 3'].apply(lambda x : x.split(' ')[0])

In [43]:
dropColumn(df,'listingCard__spec-item 3')

In [44]:
degisecekYaslar = {
    'Sıfır Bina' : '0 Yaşında'
}

df.replace(degisecekYaslar,inplace=True)

,listingCard__price,listingCard__spec-item 4,listingCard__spec-item 5,district,neighborhood,room,living_room,area
0,16.0,44 Yaşında,4. Kat,selcuklu,ihsaniye,2,1,130
1,24.0,20 Yaşında,3. Kat,selcuklu,kosova,3,1,130
2,26.0,21 Yaşında,2. Kat,selcuklu,sancak,3,1,140
3,28.0,15 Yaşında,1. Kat,selcuklu,yazir,3,1,165
4,34.0,13 Yaşında,Giriş Katı,selcuklu,sancak,3,1,150
...,...,...,...,...,...,...,...,...
492,14.0,20 Yaşında,Çatı Katı,selcuklu,kosova,1,1,90
493,18.0,20 Yaşında,Zemin,meram,yaka,3,1,160
494,25.0,6 Yaşında,1. Kat,selcuklu,kosova,1,1,70
497,5.5,15 Yaşında,3. Kat,meram,sahibiata,1,1,39
498,49.0,30 Yaşında,2. Kat,meram,askan,3,1,160

In [45]:
df['age'] = df['listingCard__spec-item 4'].apply(lambda x : x.split(" ")[0])

In [46]:
dropColumn(df,'listingCard__spec-item 4')

In [47]:
df['listingCard__spec-item 5'].unique()

<StringArray>
[      '4. Kat',       '3. Kat',       '2. Kat',       '1. Kat',
   'Giriş Katı', 'Yüksek Giriş',      'Ara Kat',       '8. Kat',
       '6. Kat',       '5. Kat',        'Zemin',            nan,
       '7. Kat',    'Çatı Katı',      '12. Kat',       '9. Kat',
      '10. Kat',        'Kot 1',  'Yarı Bodrum',   'En Üst Kat',
   'Bahçe Katı',        'Kot 3',      '13. Kat',        'Kot 2',
      '11. Kat',       'Bodrum']
Length: 26, dtype: str

In [48]:
degisecekKatlar = {
    'Giriş Katı' : '0. Kat',
    'Yüksek Giriş' : '0. Kat',
    'Ara Kat': '3 .Kat',
    'Zemin' : '0. Kat',
    'Kot 1': '-1. Kat',
    'Kot 2': '-2. Kat',
    'Kot 3': '-3. Kat',
    'Yarı Bodrum':'0. Kat',
    'Bahçe Katı' : '0. Kat',
    'Bodrum': '0. Kat',
    'Çatı Katı':'5. Kat',
    'En Üst Kat':'5. Kat',
    None : '0. Kat'
}

In [49]:
df.replace(degisecekKatlar,inplace=True)

,listingCard__price,listingCard__spec-item 5,district,neighborhood,room,living_room,area,age
0,16.0,4. Kat,selcuklu,ihsaniye,2,1,130,44
1,24.0,3. Kat,selcuklu,kosova,3,1,130,20
2,26.0,2. Kat,selcuklu,sancak,3,1,140,21
3,28.0,1. Kat,selcuklu,yazir,3,1,165,15
4,34.0,0. Kat,selcuklu,sancak,3,1,150,13
...,...,...,...,...,...,...,...,...
492,14.0,5. Kat,selcuklu,kosova,1,1,90,20
493,18.0,0. Kat,meram,yaka,3,1,160,20
494,25.0,1. Kat,selcuklu,kosova,1,1,70,6
497,5.5,3. Kat,meram,sahibiata,1,1,39,15
498,49.0,2. Kat,meram,askan,3,1,160,30

In [50]:
df['floor'] = df['listingCard__spec-item 5'].apply(lambda x:x.split('.')[0])

In [51]:
dropColumn(df,'listingCard__spec-item 5')

In [52]:
df['price'] = df['listingCard__price']

In [53]:
dropColumn(df,'listingCard__price')

In [54]:
df['price'] = df.price * 1000

In [55]:
df.info()

<class 'pandas.DataFrame'>
Index: 481 entries, 0 to 498
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   district      481 non-null    str
 1   neighborhood  481 non-null    str
 2   room          481 non-null    str
 3   living_room   481 non-null    str
 4   area          481 non-null    str
 5   age           481 non-null    str
 6   floor         481 non-null    str
 7   price         481 non-null    float64
dtypes: float64(1), str(7)
memory usage: 33.8 KB

In [56]:
df.to_csv("cleaned_data.csv",index=False)