In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'A':["ali/a/q","deneme/b/w","veli/c/r"],
    'B':[4,5,6]
    }

df = pd.DataFrame(data)

In [11]:
df['parcali'] = df['A'].apply(lambda x:x.split('/')[0:-1])

In [12]:
df['parcali']

0       [ali, a]
1    [deneme, b]
2      [veli, c]
Name: parcali, dtype: object

In [15]:
df.drop(['A'],axis=1)

   B      parcali
0  4     [ali, a]
1  5  [deneme, b]
2  6    [veli, c]

In [16]:
df

            A  B      parcali
0     ali/a/q  4     [ali, a]
1  deneme/b/w  5  [deneme, b]
2    veli/c/r  6    [veli, c]

In [19]:
df = df[df['A']!='deneme/b/w']

In [20]:
df

          A  B    parcali
0   ali/a/q  4   [ali, a]
2  veli/c/r  6  [veli, c]